Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: examples4awsbancolombialogs   
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration:
        Role: 'arn:aws:iam::275269419236:role/service-role/s3crr_role_for_examples3awsbancolombialogs'
        Rules:
          - Id: MyRule1
            Status: Enabled
            Priority: 0
            Destination:
              Bucket: 'arn:aws:s3:::my-replication-bucket'
              StorageClass: STANDARD
      LifecycleConfiguration:
        Rules:
          - Id: EstandartRule
            Prefix: Estandar
            Status: Enabled
            Transitions:
              - TransitionInDays: 1
                StorageClass: ESTANDAR